apiVersion: v1
kind: Service
metadata:
  namespace: sit
  name: bmw-register
  labels:
    app: bmw-register
spec:
  ports:
  - port: 10001
    targetPort: 10001
    protocol: TCP
  selector:
    app: bmw-register